studios:
#
#  - name: INS-STU1-PLYT             ; a UNIQUE internal string to refer to this studio
#    description: Insanity Studio 1  ; a readable description of the studio
#    ip:                             ; a list of IP addresses this studio may connect with
#        - 10.32.0.20                ;   (we shouldn't simply trust its ident)
#        - 134.219.88.20             ;
#    controller: OAC::OCP            ; the type of controller it uses (ex. OCP - Myriad) TODO HERE
#    networks:                       ; a hash of outputs that are triggered when this studio is on air
#                                    ;   (there is limited network support at this moment in time)
#        insanity: 1                 ; network: output

  - name: system
    description: Admin Socket
    ip: 
        - ::1
    type: NONE
    networks:
        insanity: 1

  - name: SU-1-1A
    description: Insanity Studio 1
    ip: 
        - 10.32.0.20
        - 134.219.88.20
    type: OAC::OCP
    macro_port: 6950
    networks:
        insanity: 1

  - name: SU-1-2A
    description: Insanity Studio 2
    ip:
        - 10.32.0.116
        - 127.0.0.1
        - 134.219.88.116
    type: OAC::OCP
    macro_port: 6950
    networks:   
        insanity: 2

controllers:
  - type: "OAC::TCP"
    network: insanity
    host: 0.0.0.0
    port: 6899
  - type: "OAC::OCP"
    network: insanity
    host: 0.0.0.0
    port: 6901

networks:
#  - name: insanity-xtra             ; UNIQUE machine readable network identifier
#    identity:
#        "OAC::OCP": "InsanityXtra"  ; the identifier for this network in playout
#    description: Insanity Xtra      ; machine readable 
#    callsign: ~                     ; 
#    control: force                  ; only allow "forced" control from playout
#        (or) none                   ; don't allow any control changes
#        (or) always                 ; let playout make a decision

  - name: insanity
    description: Insanity Radio
    callsign: Insanity Radio 103.2FM
    take_control: force
    release_control: none
    default: SU-1-1A
    switch:
      - type: "OAC::Switch::OCP"
#      - type: "OAC::Switch::OnAirNode"
#        host: 127.0.0.1
#        port: 9999
#        secret_key: todo
#        inputs:
#            0: ~
#            1: INS-STU1-PLYT
#            2: INS-STU2-PLYT
#            3: ~
#      - type: "OAC::Switch::OnAirNode"
#        host: 10.32.0.225
#        port: 9999
#        secret_key: todo
#        inputs:
#            0: ~
#            1: INS-STU1-PLYT
#            2: INS-STU2-PLYT
#            3: ~


settings:
    handover_tail: 5                 # the "tail", if supported by hardware outs. set to 0 to disable

